#include <cstddef>
constexpr size_t TRANSCRIPT_SHIFT_IS_SUBMITTED_FIRST_HALF = 1;
constexpr size_t TRANSCRIPT_SHIFT_IS_CHALLENGE_FIRST_HALF = 2;
constexpr size_t TRANSCRIPT_SHIFT_IS_SUBMITTED_SECOND_HALF = 3;
constexpr size_t TRANSCRIPT_SHIFT_IS_CHALLENGE_SECOND_HALF = 4;